### ISSUE TITLE
Theory and Code Questions

### ISSUE THREAD

**Issue by hardianlawi** [pfnet-research/capg#1]
Hi sir @muupan, 

Hope you are doing well and thank you for the wonderful paper. I didn't expect that we could learn from clipped distribution in an unbiased manner.

Few questions:

- Do you have any opinion on the performance compared to truncated gaussian? If we sample from a truncated Gaussian, we could also learn in an unbiased manner, right? I know you mentioned that truncated gaussian would always be unimodal, but I'm wondering if you have any examples that you have seen in practice where we actually prefer clipped than truncated?
- Going by the definition in your code https://github.com/pfnet-research/capg/blob/master/clipped_gaussian.py#L125, the sum of the areas under the pdf would no longer be 1. Did you implement this just because it is more convenient or I'm misunderstanding something?
- How important do you think if the gradients at the bounds are defined?

![image](https://user-images.githubusercontent.com/22806872/105814512-7f718a00-5fec-11eb-8e30-04b0375ecb9a.png)

The gradients at alpha and beta are not defined theoretically, cmiiw, but there's nothing that stops us from taking the gradients of the CDF. I would like to hear your thoughts on this as well.

Your reply would be very much appreciated. Thank you for the contribution.

**Comment by muupan** [comment]
Hi Hardian,

Thank you for your interest in our paper!

> Do you have any opinion on the performance compared to truncated gaussian?

We haven't empirically evaluated truncated Gaussian. I speculate which distribution works best would be task-dependent. In tasks where boundary actions are particularly important, I speculate clipped distribution would work better, because it can easily approximate a policy that only selects boundary actions. The opposite might be said for tasks where boundary actions are really bad.

> the sum of the areas under the pdf would no longer be 1

Clipped distribution, defined in Section 3.5, is not a continuous probability distribution because probability point masses are put on u=α and u=β. If I remember correctly, prob(u=α) + prob(u=β) + ∫[α,β]prob(u)du = 1 holds for `prob` defined in the code.

Also, the implementation of `ClippedGaussian` in the code can be just seen as a convenient way to implement our proposed gradient estimator for Gaussian as Section 3.3 says.

> How important do you think if the gradients at the bounds are defined?

When u ~ π, where π is Gaussian, the probability of u=α or u=β is zero, so I don't think it is important.

**Comment by hardianlawi** [comment]
Hi @muupan, thank you for your response. It is really helpful to me. I had some misunderstanding about the clipped distribution previously.

I will close this issue for now.
